name: Deploy PHP to Azure Web App as a Linux Web App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
# AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: ''    # set this to your application's name
  WORKING_DIRECTORY: '.'   # set this to the path to your web app project, defaults to the repository root
  PHP_VERSION: '8.1'
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    # checkout the repo
    - name: Clone ${{ env.AZURE_WEBAPP_NAME }} repo
      uses: actions/checkout@master

    # setup php
    - name: PHP ${{ env.PHP_VERSION }} Setup
      uses: actions/setup-php@v1
      with:
        php-version: ${{ env.PHP_VERSION }}

    #deploy to Azure WebApp
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.WORKING_DIRECTORY }}
