on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # Set Python version
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x' 
        architecture: 'x64'
    
    # install dependencies
    - name: python install
      run: |
        sudo apt install python3.6-venv
        python3.6 -m venv env
        source env/bin/activate
        pip3.6 install setuptools
        pip3.6 install -r requirements.txt

    # Archive built app
    - name: archive myapp
      run: |
       zip -r myapp.zip .

    # Azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation
        
    # deploy web app
    - uses: azure/webapps-deploy@v1
      with: 
        app-name: mypythonapp  # Replace with your app name
        package: './myapp.zip'

    # Add startup command in app service configuration if required

    # Azure logout 
    - name: logout
      run: |
        az logout
        
