name: Publish Universal Package to Azure Artifacts

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  ORG: ${{ vars.AZDO_ORG }}
  PROJECT: ${{ vars.AZDO_PROJECT }}
  FEED: ${{ vars.AZDO_FEED }}
  PACKAGE_NAME: my-universal-bundle
  PACKAGE_VERSION: 1.0.${{ github.run_number }}

jobs:
  universal_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Prepare the folder to publish (replace with your build output)
      - name: Build output
        run: |
          mkdir -p out
          echo "Hello $(date)" > out/info.txt

      - name: Install Azure CLI & DevOps extension
        run: |
          sudo apt-get update -y
          sudo apt-get install -y azure-cli
          az extension add -n azure-devops

      - name: Azure DevOps login (PAT)
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PKEY }}
        run: |
          #az devops configure --defaults organization="https://dev.azure.com/${{ env.ORG }}" project="${{ env.PROJECT }}"
           az devops configure --defaults organization="${{ vars.AZDO_ORG }}" project="${{ vars.AZDO_PROJECT }}"
      - name: Publish Universal Package
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PKEY }}
        run: |
          az artifacts universal publish \
            --organization "${{ vars.AZDO_ORG }}" \
            --project "${{ vars.AZDO_PROJECT }}" \
            --scope project
            --feed "${vars.AZDO_FEED}" \
            --name "${PACKAGE_NAME}" \
            --version "${PACKAGE_VERSION}" \
            --description "Published from GitHub Actions run $GITHUB_RUN_NUMBER" \
            --path out
